name: Tests CI

on:
  push:
    branches: [main, stage]
  pull_request:
    branches: [main, stage]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install uv
        run: pip install uv

      - name: Sync dependencies
        run: uv sync

      - name: Run tests with pytest
        run: pytest 